name: Validate JSON schemas

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate all json files using their own $schema properties
        uses: cardinalby/schema-validator-action@v3
        with:
          file: 'test-jsons/*.json'
          schema: 'json-schema.json'
